### ISSUE TITLE
Explicit instructions to setup a dev environment and README

### ISSUE THREAD

**Issue by meliurwen** [AlessandroBregoli/reCTBN#15]
As a potential user and new Contributor, I want a small introduction as a README, clear and explicit instructions to setup a development environment, so I can swiftly and reliably start to develop.

## Acceptance Criteria

* Full dependencies list
* Build from source
* Install from source
* Linting and testing

## Checklist

* [x]  Dependencies list
* [x]  Build from source instructions
* [x]  ~Install from source instructions~
* [x]  Linting and testing instructions
