### ISSUE TITLE
Standardized way to contribute to the project

### ISSUE THREAD

**Issue by meliurwen** [AlessandroBregoli/reCTBN#16]
As a Contributor and/or Maintainer, I want a standardized way to contribute to the project, so that the management and development becomes less chaotic and the workload for all (potential contributors, contributors and maintainers) decrease and can be more easily distributed.

## Acceptance Criteria

* Read clear and detailed contributing instructions in a dedicated section of the project
* Read clear instructions on how to submit a issue and pull request
* Read clear branch management rules

## Checklist

* [x]  Create a `CONTRIBUTING.md` file
* [x]  Bug Report instructions
* [x]  Feature Request instructions
* [x]  Pull Request instructions
* [x]  Branch management rules
