### ISSUE TITLE
Templates for the Issues and Pull Requests

### ISSUE THREAD

**Issue by meliurwen** [AlessandroBregoli/reCTBN#17]
As a potential new Contributor, I want templates to use to submit issues and pull requests, so the process is smoother and I feel more motivated to contribute.

As a Contributor, I want templates to use to submit issues and pull requests, so I can write more quickly, clearer, with reduced risk to be misunderstood and not be compliant with the guidelines.

As a Maintainer, I want templates to use to submit issues and pull requests, so the time spent to extract and keep track to the relevant information is considerably reduced.

## Acceptance Criteria

* Submit a bug using a template
* Submit a feature request using a template
* Submit a pull request to dev and master branches using a template

## Checklist

* [x]  Issue Bug template
* [x]  Issue Feature template
* [x]  Pull Request template to dev
* [x]  Pull Request template to master
