### ISSUE TITLE
[Meta] Add GitHub Workflows

### ISSUE THREAD

**Issue by meliurwen** [AlessandroBregoli/reCTBN#23]
## Description

As a contributor, I want an automated CI pipeline, so I can assure that my changes can be reliably checked in a standardized way and be more pressured to be compliant to the agreed rules.

## Acceptance Criteria

* A workflow is started as soon as I push a commit in any branch
* A workflow is started when I open a Pull Request

## Checklist

* [x] Basic Workflow with lint, build and test
* [ ] ~Add possible exceptions to the linter in order to pass~
* [x] Workflow with branch and PR rules (?)

## (Optional) Extra info

At the moment, probably a single basic CI without conditions is enough.
