### ISSUE TITLE
[Feature]  reCTBN

### ISSUE THREAD

**Issue by AlessandroBregoli** [AlessandroBregoli/reCTBN#24]
## Description

Change the name from rustyCTBN to Rust Engine for Continuous TIme Bayesian Networks (reCTBN)

## Acceptance Criteria

- Remove rustyCTBN from the entire repository and replace it with reCTBN
- ~Make an icon for the project~

## Checklist

- [x] Rename the repository
- [x] Rename the rust package
- [ ] ~Add an icon~

## (Optional) Extra info

Since *re* means *king* in italian, I would like to create an icon where there is Ferris with a crown.
