### ISSUE TITLE
[Meta] Explicitly declare labels on a file and automate the edits to the project's settings

### ISSUE THREAD

**Issue by meliurwen** [AlessandroBregoli/reCTBN#38]
## Description

As a maintainer, I want to explicitly declare labels on a file, so I can keep track of eventual changes, eventual migrations to other platforms would be smoother and contributors which doesn't have access to the settings of this project can edit them.

## Acceptance Criteria

* Edit labels exclusively via git

## Checklist

* [x] Add `.github/labels.yml`
* [x] Add `.github/workflows/labels.yml`
* [x] Add `refactor` label to refactor issue template
* [x] Comment title in PR to dev template

## (Optional) Extra info

Additionally comment title in PR to dev template and add `refactor` label to refactor issue template
