### ISSUE TITLE
[Meta] Add rustfmt in GitHub Workflows

### ISSUE THREAD

**Issue by meliurwen** [AlessandroBregoli/reCTBN#52]
## Description

As a contributor, I want an automated tool that checks the Rust code formatting is according to style guidelines, so I can assure that my changes can be reliably checked in a standardized way and be more pressured to be compliant to the agreed rules.

## Acceptance Criteria

* The workflow fails if I push code not formatted according to the style guidelines
* The check succeds if I push code formatted according to the style guidelines

## Checklist

* [x] rustfmt step in `build.yml`
* [x] Add `rustfmt.toml`
* [x] Update the README with instructions on how to locally use `rustfmt`

## (Optional) Extra info

See the [rustfmt official docs](https://rust-lang.github.io/rustfmt).
